language: go

services:
  - docker

env:
  - GO111MODULE=on

go:
  - "1.11.x"

script:
  - make docker VERSION=$TRAVIS_BRANCH
  - docker images | grep scnewma/nest_exporter

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make docker-publish
  on:
    branch: master
